DROP TABLE IF EXISTS education_material;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS document;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS role;
